[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.98"
authors = ["Jake Van Slyke <jakervanslyke@gmail.com>"]
license = "MIT"
repository = "https://github.com/jakeryderv/pyprojx"

[workspace.dependencies]
pyprojx_core = { path = "crates/pyprojx_core" }

clap = { version = "4.6.7", features = ["derive"] }
toml = { version = "1.1.6", default-features = false, features = ["std", "parse", "preserve_order"] }
toml-test-data = "2.14.1"

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
strip = true
