[package]
name = "pyprojx_core"
description = "Core analysis library for pyprojx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
strsim.workspace = true
toml.workspace = true
toml_parser.workspace = true
url.workspace = true
uv-normalize.workspace = true
uv-pep440.workspace = true
uv-pep508.workspace = true

[dev-dependencies]
insta.workspace = true
toml-test-data.workspace = true

[lints]
workspace = true
