[package]
name = "pyprojx_core"
description = "Core analysis library for pyprojx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
toml.workspace = true
toml_parser.workspace = true

[dev-dependencies]
toml-test-data.workspace = true

[lints]
workspace = true
