"""Generate pyprojx's embedded list of trove classifiers.

The list comes from the `trove-classifiers` package locked in uv.lock, which
Dependabot keeps current. Run after updating it:

    uv run --locked python scripts/update_classifiers.py

With `--check`, exits with an error if the generated file is out of date.
"""

import argparse
import importlib.metadata
import sys
from pathlib import Path

import trove_classifiers

OUTPUT = Path(__file__).resolve().parents[1] / "crates/pyprojx_core/src/trove_data.rs"


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate() -> str:
    version = importlib.metadata.version("trove-classifiers")
    lines = [
        "// @generated by scripts/update_classifiers.py; do not edit.",
        "",
        "/// The `trove-classifiers` release this data comes from.",
        f"pub const VERSION: &str = {rust_string(version)};",
        "",
        "/// Classifiers accepted by PyPI, sorted.",
        "pub const CLASSIFIERS: &[&str] = &[",
    ]
    lines += [f"    {rust_string(name)}," for name in sorted(trove_classifiers.classifiers)]
    lines += [
        "];",
        "",
        "/// Deprecated classifiers and their replacements, sorted.",
        "pub const DEPRECATED: &[(&str, &[&str])] = &[",
    ]
    for name, replacements in sorted(trove_classifiers.deprecated_classifiers.items()):
        items = ", ".join(rust_string(item) for item in replacements)
        lines.append(f"    ({rust_string(name)}, &[{items}]),")
    lines += ["];", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args()
    content = generate()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if args.check:
        if current != content:
            print(
                f"{OUTPUT.name} is out of date; run `uv run --locked python scripts/update_classifiers.py`",
                file=sys.stderr,
            )
            return 1
        return 0
    if current != content:
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"updated {OUTPUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
