# /// script
# requires-python = ">=3.11"
# dependencies = ["packaging"]
# ///
"""Generate pyprojx's data about ty's configuration across releases.

For every ty release, reads the JSON schema of its configuration and records
which releases accept and deprecate each option and which rules each release
knows. ty's source is in the Ruff repository, which each ty release pins as a
submodule; the schema is `ty.schema.json` at that commit.

Schemas are cached, so later runs only download new releases. The script needs
the network, so it runs on a schedule (.github/workflows/tool-data.yml) rather
than in CI, or by hand:

    uv run scripts/update_ty_data.py
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import subprocess
import sys

from packaging.version import Version
from schema_history import (
    CACHE,
    ROOT,
    add_aliases,
    collect,
    example,
    fetch,
    generate_options,
    probe,
    ranges,
    releases,
    rust_ranges,
    rust_string,
    setting,
)

OUTPUT = ROOT / "crates/pyprojx_core/src/ty_data.rs"
FIRST = Version("0.0.2")
TY_CACHE = CACHE / "ty"
REPOSITORY = TY_CACHE / "ty.git"


def ruff_commits(versions: list[Version]) -> dict[Version, str]:
    """The Ruff commit each ty release pins, from a treeless clone of ty."""
    if REPOSITORY.exists():
        subprocess.run(
            ["git", "-C", REPOSITORY, "fetch", "--quiet", "--tags", "origin"],
            check=True,
        )
    else:
        REPOSITORY.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            [
                "git",
                "clone",
                "--quiet",
                "--bare",
                "--filter=tree:0",
                "https://github.com/astral-sh/ty",
                REPOSITORY,
            ],
            check=True,
        )
    commits = {}
    for version in versions:
        output = subprocess.run(
            ["git", "-C", REPOSITORY, "ls-tree", str(version), "ruff"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout
        # `160000 commit <sha>\truff`
        commits[version] = output.split()[2]
    return commits


def schema(version: Version, commit: str) -> dict:
    url = f"https://raw.githubusercontent.com/astral-sh/ruff/{commit}/ty.schema.json"
    content = fetch([url], TY_CACHE / f"{version}.schema.json")
    if content is None:
        raise RuntimeError(f"no schema for ty {version} at Ruff commit {commit}")
    return json.loads(content)


def check(version: Version, config: str) -> str:
    """ty's output when a release checks a file with the given configuration."""
    return probe(
        TY_CACHE / "probes.json",
        ["uvx", "--quiet", f"ty@{version}", "check", "--no-progress", "a.py"],
        {
            "a.py": "x = 1\n",
            "pyproject.toml": f'[project]\nname = "demo"\nversion = "1"\n{config}',
        },
    ).output


def rules(document: dict) -> list[str]:
    """The rules a release knows, which `rules` tables configure."""
    return list(document["definitions"]["Rules"]["properties"])


def generate(versions, found, messages, known_rules: dict[str, list[int]]) -> str:
    lines = [
        "// @generated by scripts/update_ty_data.py; do not edit.",
        "",
        "use crate::tool::{OptionData, OptionKind, ValueType};",
        "",
    ]
    lines += generate_options("ty", versions, found, messages)
    lines += [
        "/// Rule names with the releases that know them, sorted.",
        "pub const RULES: &[(&str, &[(u16, u16)])] = &[",
    ]
    lines += [
        f"    ({rust_string(rule)}, {rust_ranges(ranges(known_rules[rule]))}),"
        for rule in sorted(known_rules)
    ]
    lines += ["];", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.parse_args()
    versions = releases("ty", FIRST)
    commits = ruff_commits(versions)
    with concurrent.futures.ThreadPoolExecutor(8) as pool:
        schemas = list(pool.map(lambda v: schema(v, commits[v]), versions))
    found = collect(versions, schemas)

    def accepts(index: int, path: str) -> bool:
        option = found[path]
        value = example(option.types.get(option.present[-1]), option.kind)
        config = setting("tool.ty", found, path, value)
        return "ty failed" not in check(versions[index], config)

    messages = add_aliases(found, versions, accepts)
    known_rules: dict[str, list[int]] = {}
    for index, document in enumerate(schemas):
        for rule in rules(document):
            known_rules.setdefault(rule, []).append(index)
    OUTPUT.write_text(
        generate(versions, found, messages, known_rules), encoding="utf-8"
    )
    print(
        f"wrote {len(found)} options and {len(known_rules)} rules "
        f"across {len(versions)} releases to {OUTPUT}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
