[package]
name = "pyprojx"
description = "Version-aware intelligence for pyproject.toml"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
pyprojx_core.workspace = true

annotate-snippets.workspace = true
anstream.workspace = true
clap.workspace = true
similar.workspace = true

[dev-dependencies]
insta.workspace = true
insta-cmd.workspace = true
tempfile.workspace = true

[lints]
workspace = true
