// @generated by scripts/calibrate_backends.py; do not edit.
// Calibrated on 2026-09-24 with uv 0.12.18 and Python 3.11.

use crate::backends::{BackendData, Feature, FeatureSupport, Since};

pub const BACKENDS: &[BackendData] = &[
    BackendData {
        name: "setuptools",
        module: "setuptools.build_meta",
        first: "0.7.2",
        latest: "84.0.0",
        features: &[
            // Supported: 0.7.2 fails, 5.2 fails, 18.3 fails, 25.1.0 fails, 35.0.0 fails, 38.7.0 fails, 41.0.1 fails, 51.3.1 ignored, 60.8.0 ignored, 60.9.1 ignored, 60.9.3 ignored, 60.10.0 ignored, 61.0.0 yes, 61.1.0 yes, 62.3.1 yes, 63.3.0 yes, 65.0.0 yes, 65.6.1 yes, 67.7.2 yes, 68.2.1 yes, 70.0.0 yes, 75.1.0 yes, 78.1.0 yes, 84.0.0 yes.
            FeatureSupport { feature: Feature::ProjectTable, since: Since::Version { before: "60.10.0", version: "61.0.0" }, fails: false },
            // Supported: 0.7.2 fails, 8.0.3 fails, 20.7.0 fails, 33.1.1 fails, 38.7.0 fails, 41.3.0 fails, 57.5.0 ignored, 60.8.0 ignored, 65.3.0 fails, 68.2.1 fails, 75.3.1 fails, 75.8.1 fails, 75.9.1 fails, 76.0.0 fails, 76.1.0 fails, 77.0.1 yes, 78.0.2 yes, 78.1.1 yes, 79.0.1 yes, 80.1.0 yes, 80.6.0 yes, 80.9.0 yes, 82.0.0 yes, 84.0.0 yes.
            FeatureSupport { feature: Feature::LicenseExpression, since: Since::Version { before: "76.1.0", version: "77.0.1" }, fails: true },
            // Supported: 0.7.2 fails, 8.0.3 fails, 20.7.0 fails, 33.1.1 fails, 38.7.0 fails, 41.3.0 fails, 57.5.0 ignored, 60.8.0 ignored, 65.3.0 fails, 68.2.1 fails, 75.3.1 fails, 75.8.1 fails, 75.9.1 fails, 76.0.0 fails, 76.1.0 fails, 77.0.1 yes, 78.0.2 yes, 78.1.1 yes, 79.0.1 yes, 80.1.0 yes, 80.6.0 yes, 80.9.0 yes, 82.0.0 yes, 84.0.0 yes.
            FeatureSupport { feature: Feature::LicenseFiles, since: Since::Version { before: "76.1.0", version: "77.0.1" }, fails: true },
        ],
    },
    BackendData {
        name: "hatchling",
        module: "hatchling.build",
        first: "0.8.0",
        latest: "1.32.4",
        features: &[
            // Supported: 0.8.0 yes, 0.14.0 yes, 0.22.0 yes, 1.5.0 yes, 1.12.1 yes, 1.19.0 yes, 1.24.1 yes, 1.32.4 yes.
            FeatureSupport { feature: Feature::ProjectTable, since: Since::First, fails: false },
            // Supported: 0.8.0 ignored, 0.13.0 ignored, 0.21.0 ignored, 1.3.0 ignored, 1.8.1 ignored, 1.9.0 ignored, 1.15.0 ignored, 1.21.0 ignored, 1.21.1 ignored, 1.24.2 ignored, 1.26.3 ignored, 1.27.0 yes, 1.28.0 yes, 1.29.0 yes, 1.30.1 yes, 1.31.0 yes, 1.32.0 yes, 1.32.3 yes, 1.32.4 yes.
            FeatureSupport { feature: Feature::LicenseExpression, since: Since::Version { before: "1.26.3", version: "1.27.0" }, fails: false },
            // Supported: 0.8.0 fails, 0.13.0 fails, 0.21.0 fails, 1.3.0 fails, 1.8.1 fails, 1.9.0 fails, 1.15.0 fails, 1.21.0 fails, 1.21.1 fails, 1.24.2 fails, 1.26.3 ignored, 1.27.0 yes, 1.28.0 yes, 1.29.0 yes, 1.30.1 yes, 1.31.0 yes, 1.32.0 yes, 1.32.3 yes, 1.32.4 yes.
            FeatureSupport { feature: Feature::LicenseFiles, since: Since::Version { before: "1.26.3", version: "1.27.0" }, fails: false },
        ],
    },
    BackendData {
        name: "flit-core",
        module: "flit_core.buildapi",
        first: "2.0",
        latest: "4.1.0",
        features: &[
            // Supported: 2.0 fails, 2.0.1 fails, 2.0.2 fails, 2.1.0 fails, 2.2.0 fails, 2.3.0 fails, 3.0.0 fails, 3.1.0 fails, 3.2.0 yes, 3.3.0 yes, 3.4.0 yes, 3.5.1 yes, 3.6.0 yes, 3.7.1 yes, 3.9.0 yes, 3.10.1 yes, 4.0.1 yes, 4.1.0 yes.
            FeatureSupport { feature: Feature::ProjectTable, since: Since::Version { before: "3.1.0", version: "3.2.0" }, fails: false },
            // Supported: 2.0 fails, 2.1.0 fails, 2.3.0 fails, 3.2.0 fails, 3.5.0 fails, 3.5.1 fails, 3.7.0 fails, 3.8.0 fails, 3.10.0 fails, 3.10.1 fails, 3.11.0 yes, 3.12.0 yes, 4.0.1 yes, 4.0.2 yes, 4.1.0 yes.
            FeatureSupport { feature: Feature::LicenseExpression, since: Since::Version { before: "3.10.1", version: "3.11.0" }, fails: true },
            // Supported: 2.0 fails, 2.1.0 fails, 2.3.0 fails, 3.2.0 ignored, 3.5.0 ignored, 3.5.1 ignored, 3.7.0 ignored, 3.8.0 ignored, 3.10.0 ignored, 3.10.1 ignored, 3.11.0 yes, 3.12.0 yes, 4.0.1 yes, 4.0.2 yes, 4.1.0 yes.
            FeatureSupport { feature: Feature::LicenseFiles, since: Since::Version { before: "3.10.1", version: "3.11.0" }, fails: false },
        ],
    },
    BackendData {
        name: "pdm-backend",
        module: "pdm.backend",
        first: "0.0.0",
        latest: "2.4.10",
        features: &[
            // Supported: 0.0.0 yes, 2.0.5 yes, 2.1.1 yes, 2.1.6 yes, 2.2.1 yes, 2.4.1 yes, 2.4.5 yes, 2.4.10 yes.
            FeatureSupport { feature: Feature::ProjectTable, since: Since::First, fails: false },
            // Supported: 0.0.0 fails, 2.0.2 fails, 2.0.6 fails, 2.1.1 fails, 2.1.5 fails, 2.1.8 fails, 2.3.0 fails, 2.3.1 fails, 2.3.3 fails, 2.4.1 yes, 2.4.2 yes, 2.4.4 yes, 2.4.5 yes, 2.4.6 yes, 2.4.7 yes, 2.4.9 yes, 2.4.10 yes.
            FeatureSupport { feature: Feature::LicenseExpression, since: Since::Version { before: "2.3.3", version: "2.4.1" }, fails: true },
            // Supported: 0.0.0 fails, 2.0.2 fails, 2.0.6 fails, 2.1.1 fails, 2.1.5 fails, 2.1.8 fails, 2.3.0 fails, 2.3.1 fails, 2.3.3 fails, 2.4.1 yes, 2.4.2 yes, 2.4.4 yes, 2.4.5 yes, 2.4.6 yes, 2.4.7 yes, 2.4.9 yes, 2.4.10 yes.
            FeatureSupport { feature: Feature::LicenseFiles, since: Since::Version { before: "2.3.3", version: "2.4.1" }, fails: true },
        ],
    },
    BackendData {
        name: "poetry-core",
        module: "poetry.core.masonry.api",
        first: "1.0.0",
        latest: "2.5.0",
        features: &[
            // Supported: 1.0.0 fails, 1.0.3 fails, 1.0.7 fails, 1.2.0 fails, 1.4.0 fails, 1.5.2 fails, 1.6.1 fails, 1.8.0 fails, 1.9.0 fails, 1.9.1 fails, 2.0.0 yes, 2.1.0 yes, 2.1.1 yes, 2.1.2 yes, 2.2.0 yes, 2.2.1 yes, 2.3.1 yes, 2.4.0 yes, 2.5.0 yes.
            FeatureSupport { feature: Feature::ProjectTable, since: Since::Version { before: "1.9.1", version: "2.0.0" }, fails: false },
            // Supported: 1.0.0 fails, 1.0.4 fails, 1.0.8 fails, 1.3.2 fails, 1.6.0 fails, 1.6.1 fails, 1.8.1 fails, 2.0.1 ignored, 2.1.1 ignored, 2.1.3 ignored, 2.2.0 yes, 2.2.1 yes, 2.3.0 yes, 2.3.1 yes, 2.3.2 yes, 2.4.0 yes, 2.4.1 yes, 2.5.0 yes.
            FeatureSupport { feature: Feature::LicenseExpression, since: Since::Version { before: "2.1.3", version: "2.2.0" }, fails: false },
            // Supported: 1.0.0 fails, 1.0.4 fails, 1.0.8 fails, 1.3.2 fails, 1.6.0 fails, 1.6.1 fails, 1.8.1 fails, 2.0.1 ignored, 2.1.1 ignored, 2.1.3 ignored, 2.2.0 yes, 2.2.1 yes, 2.3.0 yes, 2.3.1 yes, 2.3.2 yes, 2.4.0 yes, 2.4.1 yes, 2.5.0 yes.
            FeatureSupport { feature: Feature::LicenseFiles, since: Since::Version { before: "2.1.3", version: "2.2.0" }, fails: false },
        ],
    },
    BackendData {
        name: "uv-build",
        module: "uv_build",
        first: "0.6.6",
        latest: "0.12.18",
        features: &[
            // Supported: 0.6.6 yes, 0.7.10 yes, 0.8.10 yes, 0.9.7 yes, 0.9.29 yes, 0.11.7 yes, 0.11.30 yes, 0.12.18 yes.
            FeatureSupport { feature: Feature::ProjectTable, since: Since::First, fails: false },
            // Supported: 0.6.6 yes, 0.7.10 yes, 0.8.10 yes, 0.9.7 yes, 0.9.29 yes, 0.11.7 yes, 0.11.30 yes, 0.12.18 yes.
            FeatureSupport { feature: Feature::LicenseExpression, since: Since::First, fails: false },
            // Supported: 0.6.6 yes, 0.7.10 yes, 0.8.10 yes, 0.9.7 yes, 0.9.29 yes, 0.11.7 yes, 0.11.30 yes, 0.12.18 yes.
            FeatureSupport { feature: Feature::LicenseFiles, since: Since::First, fails: false },
        ],
    },
];
